### ISSUE TITLE
No example in doc

### ISSUE THREAD

**Issue by drankard** [aws-samples/apprunner-hotel-app#4]
Hi there. 
I struggle to se how i map the secret attributes to the environment variables.
The secret (normal RDS secrets) contain a JSON object with username, password, host & port attributes

In your doc you write:
MYSQL_HOST: DBSecret ARN (Provisioned by infra.yaml. See Outputs tab)
but mapping to the secret arn, will not map the values to env variabe? 
How do i get the attributes mapped in the secret set to the variables? 

This fail:
MYSQL_HOST: `arn:aws:secretsmanager:<region>:<account>:secret:<secret>:<secret_attribute>`

Can you please update the documentation on how this is mapped ?

**Comment by srijitm** [comment]
Hi @drankard,

Please take a look at the [rds.js](https://github.com/aws-samples/apprunner-hotel-app/blob/main/rds.js) file to see how we achieve this.

We parse the JSON object and use the attributes to set up the DB connection.

**Comment by drankard** [comment]
Ah ok, this means that i have to do this myself in my impl, I guess this is ok in most cases. i thought that some resolver pattern was avalilable. - like when im deploying docker images that only need env vars to run, like the official phpmyadmin image,  this way i need to extend the image and host it in ECR i cannot just use it as is.

Thanks for the pointer.

**Comment by srijitm** [comment]
If you store the variables in Parameter Store as  secure strings, then the exact value will be injected into the environment variable. Secure Strings in parameter store are also encrypted with KMS. However, Parameter Store does not have the native integration with RDS.
